% Gap fill and smooth the NDVI time series using smoothn, a 3D smoothing algorithm by Damien Garcia

mat_files = { ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b001.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b002.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b003.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b004.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b005.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b006.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b007.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b008.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b009.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b010.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b011.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b012.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b013.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b014.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b015.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b016.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b017.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b018.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b019.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b020.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b021.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b022.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b023.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b024.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b025.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b026.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b027.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b028.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b029.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b030.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b031.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b032.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b033.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b034.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b035.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b036.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b037.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b038.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b039.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b040.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b041.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b042.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b043.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b044.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b045.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b046.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b047.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b048.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b049.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b050.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b051.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b052.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b053.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b054.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b055.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b056.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b057.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b058.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b059.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b060.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b061.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b062.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b063.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b064.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b065.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b066.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b067.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b068.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b069.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b070.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b071.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b072.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b073.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b074.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b075.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b076.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b077.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b078.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b079.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b080.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b081.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b082.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b083.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b084.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b085.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b086.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b087.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b088.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b089.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b090.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b091.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b092.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b093.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b094.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b095.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b096.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b097.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b098.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b099.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b100.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b101.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b102.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b103.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b104.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b105.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b106.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b107.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b108.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b109.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b110.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b111.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b112.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b113.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b114.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b115.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b116.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b117.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b118.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b119.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b120.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b121.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b122.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b123.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b124.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b125.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b126.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b127.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b128.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b129.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b130.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b131.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b132.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b133.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b134.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b135.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b136.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b137.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b138.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b139.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b140.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b141.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b142.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b143.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b144.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b145.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b146.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b147.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b148.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b149.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b150.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b151.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b152.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b153.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b154.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b155.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b156.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b157.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b158.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b159.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b160.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b161.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b162.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b163.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b164.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b165.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b166.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b167.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b168.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b169.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b170.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b171.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b172.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b173.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b174.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b175.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b176.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b177.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b178.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b179.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b180.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b181.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b182.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b183.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b184.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b185.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b186.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b187.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b188.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b189.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b190.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b191.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b192.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b193.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b194.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b195.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b196.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b197.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b198.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b199.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b200.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b201.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b202.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b203.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b204.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b205.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b206.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b207.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b208.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b209.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b210.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b211.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b212.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b213.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b214.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b215.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b216.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b217.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b218.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b219.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b220.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b221.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b222.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b223.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b224.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b225.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b226.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b227.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b228.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b229.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b230.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b231.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b232.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b233.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b234.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b235.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b236.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b237.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b238.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b239.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b240.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b241.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b242.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b243.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b244.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b245.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b246.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b247.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b248.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b249.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b250.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b251.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b252.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b253.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b254.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b255.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b256.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b257.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b258.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b259.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b260.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b261.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b262.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b263.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b264.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b265.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b266.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b267.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b268.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b269.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b270.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b271.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b272.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b273.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b274.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b275.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b276.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b277.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b278.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b279.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b280.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b281.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b282.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b283.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b284.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b285.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b286.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b287.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b288.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b289.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b290.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b291.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b292.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b293.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b294.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b295.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b296.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b297.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b298.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b299.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b300.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b301.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b302.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b303.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b304.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b305.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b306.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b307.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b308.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b309.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b310.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b311.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b312.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b313.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b314.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b315.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b316.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b317.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b318.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b319.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b320.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b321.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b322.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b323.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b324.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b325.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b326.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b327.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b328.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b329.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b330.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b331.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b332.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b333.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b334.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b335.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b336.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b337.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b338.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b339.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b340.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b341.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b342.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b343.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b344.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b345.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b346.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b347.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b348.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b349.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b350.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b351.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b352.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b353.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b354.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b355.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b356.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b357.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b358.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b359.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b360.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b361.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b362.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b363.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b364.mat'; ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_b365.mat'; ...
};

% mat_profile_file = '/projectnb/echidna/lidar/zhanli86/workspace/data/projects/kaiyu-adb-crop/vietnam-fusion-ts/mat-files/predicted_ndvi_profile.mat';

addpath('/usr3/graduate/zhanli86/Workspace/src/projects/adb-paddy-rice-thai-binh/scripts/smoothn');

% no data value
no_data = -9999;

% get the dimension of the image
load(mat_files{1});
[nrows, ncols] = size(predicted_ndvi_b001);
[ndays, dummy] = size(mat_files);

[dummy, ndigits] = size(num2str(ndays));
% ndays = 3; ndigits = 3;
fmtstr = sprintf('%%0%dd', ndigits);

data = NaN([nrows, ncols, ndays], 'single');
weight = ones([nrows, ncols, ndays], 'single');

fprintf('Start loading data\n');
for n=1:ndays
  load(mat_files{n});
  tmp = eval(sprintf(['predicted_ndvi_b', fmtstr], n));
  tmp(tmp == no_data) = NaN;
  tmp(tmp <=0) = NaN;
  data(:, :, n) = tmp;
  tmp(isnan(tmp)) = 0; 
  weight(:, :, n) = tmp;
end

fprintf('Start smoothn\n');
% [data_s, dummy, exit_flag] = smoothn(data, weight, 1e-6);
[data_s, s, exit_flag] = smoothn(data, weight, []);

fprintf('Exit flag = %d\n', exit_flag);
fprintf('GCV-selected smoothing parameter = %.3f\n', s);

fprintf('Start saving results\n');
for n=1:ndays
  [pathstr, fname, ext] = fileparts(mat_files{n});
  out_fname = fullfile(pathstr, ['smoothn_', fname, ext]);
  eval(sprintf(['smoothn_predicted_ndvi_b', fmtstr, '= data_s(:, :, n);'], n));
  save(out_fname, sprintf(['smoothn_predicted_ndvi_b', fmtstr], n), '-v7');
end

fprintf('NDVI time series smoothn finished.\n');
